# Changes here will be overwritten by Copier
AddAllcontributors: true
AddCodeOfConduct: true
AddContributionDocs: true
AddCopierCI: true
AddGitHubTemplates: true
AddMacToCI: true
AddPrecommit: true
AddWinToCI: true
AnswerStrategy: ask
Authors: Miguel Raz miguelraz@ciencias.unam.mx
AutoIncludeTests: true
CheckExplicitImports: true
CodeOfConductContact: Miguel Raz miguelraz@ciencias.unam.mx
ConfigIndentation: 2
ExplicitImportsChecklist: exclude_all_qualified_accesses_are_public
JuliaIndentation: 4
JuliaMinCIVersion: lts
JuliaMinVersion: '1.10'
License: MIT
LicenseCopyrightHolders: Miguel Raz miguelraz@ciencias.unam.mx
MarkdownIndentation: 2
PackageName: ComplexDiff
PackageOwner: miguelraz
PackageUUID: 1d1de044-f46f-5800-b4a4-9afccb2ed989
RunJuliaNightlyOnCI: false
UseCirrusCI: false
_commit: v0.14.0
_src_path: https://github.com/JuliaBesties/BestieTemplate.jl
